### ISSUE TITLE
Key press events not received

### ISSUE THREAD

**Issue by avaly** [pkkid/pygrid#11]
Does any one else experience that key presses are no longer received by `pygrid`? 

I'm on Ubuntu 18.04.1 LTS, and it did work until recently.

**Comment by pkkid** [comment]
Still working for me. Are you by any chance using Wayland?

**Comment by avaly** [comment]
TIL about Wayland.

It was appearantly running. I disabled it, but I still get no key press events in pygrid.

Any thoughts on how to debug this?

**Comment by pkkid** [comment]
Wayland is a display manager like X. So you are either running Wayland or X to display your the windows on your screen. It's a choice when you log into the OS after booting up. This app currently only works with X.

See here: https://itsfoss.com/switch-xorg-wayland/

**Comment by avaly** [comment]
A few days ago, it started working again as expected. Although I haven't changed any setup on my laptop. :man_shrugging:

**Comment by avaly** [comment]
This is happening again for me on a fresh install of Ubuntu 18.04.2.

**Comment by avaly** [comment]
I'm still getting this behavior on a fresh install of Ubuntu 20.04.

**Comment by avaly** [comment]
It seems my issue was related to the `accelerator` key. I had previously configured it to `<Ctrl><Mod2><Mod4>`, which worked on Ubuntu 18.04 (on a different laptop). On my new laptop running Ubuntu 20.04, I had to modify this to `<Ctrl><Mod4>` for it to work when pressing Ctrl+Super.

**Comment by pkkid** [comment]
Glad you figured this out and thanks for documenting your notes here for future users.
