### ISSUE TITLE
Pygrid doesn't work on laptop

### ISSUE THREAD

**Issue by SimonDedman** [pkkid/pygrid#15]
I'm running X11, on a laptop with no numpad keys and thus no numlock, I changed my config to:

```
    "accelerator": "<Mod1><Mod4>",
    "commands": {
      "Prior": "maximize",
      "KP_1": "bottomleft",
      "Down": "bottom",
      "KP_3": "bottomright",
      "Left": "left",
      "KP_5": "middle",
      "Right": "right",
      "KP_7": "topleft",
      "Up": "top",
      "KP_9": "topright",
      "Next": "cycle-monitor"
```
But with Pygrid running, nothing happens. I've verified super+alt+? combinations work in keyboard application shortcuts, and have tried a variety of more normal keys (e.g. 0) instead of Right Left etc. But nothing happens. If I try super+alt+Left on a terminal window, those commands are pasted into the terminal rather than moving the terminal window.

Any ideas why this might be? Thanks.

**Comment by simmihugs** [comment]
In my case, I use a linux distro called solus, It works with the following json, that I can use 
windowskey + j for left tile and so on. I use a 2x2 grid not 3x2 as the default.

```
{
  "default": {
    "maxheight": 0.67,
    "maxwidth": 0.67,
    "minheight": 0.33,
    "minwidth": 0.25,
    "padding": [
      0,
      0,
      0,
      0
    ],
    "snaptocursor": false,
    "spacing": 4,
    "xdivs": 2,
    "ydivs": 2
  },
  "keys": {
    "accelerator": "<Mod4><Mod2>",
    "commands": {
      "m": "maximize",
      "l": "bottomleft",
      "b": "bottom",
      "o": "bottomright",
      "j": "left",
      "KP_4": "middle",
      "k": "right",
      "u": "topleft",
      "t": "top",
      "i": "topright",
      "KP_Enter": "cycle-monitor"
    }
  }
}
```

**Comment by simmihugs** [comment]
This setup on my machine makes Alt + Windowskey + leftarrow tile to the left
Mod1 = alt
Mod4 = Windowskey
Mod2 = I have no clue, but without it nothing happens; 
```
  "keys": {
    "accelerator": "<Mod1><Mod4><Mod2>",
    "commands": {
      "m": "maximize",
      "l": "bottomleft",
      "Down": "bottom",
      "o": "bottomright",
      "Left": "left",
      "KP_4": "middle",
      "Right": "right",
      "u": "topleft",
      "Up": "top",
      "i": "topright",
      "KP_Enter": "cycle-monitor"
    }
  }
}
```

**Comment by SimonDedman** [comment]
Simmi you absolute legend. The mystery Mod2 did the trick. Cheers!!
