### ISSUE TITLE
Titlebar disappears when maximizing window

### ISSUE THREAD

**Issue by dol** [pkkid/pygrid#3]
The title bar of an window disappears when maximizing a window that was resize with pyGrid.

Reproduce the issue:
1. Open new window
2. Unmaximize window
3. Use Ctrl+Alt+5 to align/resize window
4. Maximize the window
## Expected

![screenshot_2016-10-10_22-50-49](https://cloud.githubusercontent.com/assets/41777/19250710/22a153e4-8f3c-11e6-8aad-a3401d8621ae.png)
## Actual

![screenshot_2016-10-10_22-50-18](https://cloud.githubusercontent.com/assets/41777/19250724/342be8cc-8f3c-11e6-88f7-17cce4702154.png)

**Comment by dol** [comment]
Additional informations:

- XFCE 4.12.2
- Same behavior for every window
- Same behavior on every monitor (with or without top or bottom panel)

**Comment by mjs7231** [comment]
Interesting.  It sounds like I'll have to spin up a VM with XFCE on it.  If you don't mind a minor code change, I suspect commenting out line 181 (`window.set_shadow_width(0,0,0,0)`) might fix the issue. It's a workaround for bug #1 dealing with window shadows.

**Comment by dol** [comment]
Commenting out `window.set_shadow_width(0,0,0,0)` solved the problem. No a workaround of a workaround is needed.
![workaround](https://cdn.meme.am/instances/66895126.jpg)

**Comment by pkkid** [comment]
This is slightly icky, but maybe the best option for now is to have a configuration option to enable or disable the shadow workaround we need for Gnome but you don't want on XFCE. I'm going to dupe this bug to the other one since they are basically dealing with the same line of code.

See: https://github.com/pkkid/pygrid/issues/1
