### ISSUE TITLE
Maximize shortcut is really minimizing window

### ISSUE THREAD

**Issue by pkkid** [pkkid/pygrid#8]
The shortcut to maximize the window is really minimizing the window for me on Ubuntu 17.10.

**Comment by avaly** [comment]
:( I've only tested it on my Ubuntu 16.04.

**Comment by pkkid** [comment]
I figure it's just an environment thing. When I free time, we can dig in more to see whats up. Thanks again for the contribution. :D

**Comment by pkkid** [comment]
This seems to be working fine for me on Ubuntu 18.04. Not sure whats up with my home PC.
