### ISSUE TITLE
Cycle Monitor shortcut not working

### ISSUE THREAD

**Issue by pkkid** [pkkid/pygrid#9]
The cycle monitor shortcut is not doing anything for me on Ubuntu 17.10.

**Comment by avaly** [comment]
:( I've only tested it on my Ubuntu 16.04.

**Comment by pckilgore** [comment]
Works fine on 18.04?

**Comment by pkkid** [comment]
This seems to be working fine for me on Ubuntu 18.04. Not sure whats up with my home PC.
